CREATE TABLE IF NOT EXISTS favorites (
    FavoriteID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    TicketID INT NOT NULL,
    CreatedTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES users(UserID) ON DELETE CASCADE,
    FOREIGN KEY (TicketID) REFERENCES tickets(TicketID) ON DELETE CASCADE,
    UNIQUE KEY unique_user_ticket (UserID, TicketID)
);

